### ISSUE TITLE
Reporter says upload done, no data reaches codeclimate?

### ISSUE THREAD

**Issue by krodyrobi** [codeclimate/python-test-reporter#23]
I've got a question regarding what could go wrong when the script says an upload is done but in fact codeclimate still tells me that test coverage was not setup. As can be seen the same commit sha is present in both screen shots.

![screenshot from 2016-06-14 19 10 59](https://cloud.githubusercontent.com/assets/4136467/16050287/c31f7944-3263-11e6-8153-9186852459a7.png)

![screenshot from 2016-06-14 19 12 29](https://cloud.githubusercontent.com/assets/4136467/16050338/f7f1aff2-3263-11e6-82de-1e6a03a88a01.png)

**Comment by dblandin** [comment]
Thanks for the report!

It looks like our inferred git data from drone CI environment variables [is misconfigured](). This also doesn't seem specific to this test reporter. We unfortunately have the same misconfigured inference [in our ruby-test-reporter][].

[is misconfigured]: https://github.com/codeclimate/python-test-reporter/blob/c498653162a4ef6156e70d8a3576d35a7edd38e7/codeclimate_test_reporter/components/ci.py#L88
[in our ruby-test-reporter]: https://github.com/codeclimate/ruby-test-reporter/blob/4e29518840cb56d69bc8b591ded30e7ec5552e66/lib/code_climate/test_reporter/ci.rb#L63

To confirm, I checked out logs and I can see the build number instead of the appropriate git commit sha in your test report payload:

```
POST /test_reports 200 OK
```
```json
{ "git": {"head": "13", "committed_at": "1465901227", "branch": "master"}
```

I'll get a patch released soon but in the meantime, a workaround would be to unset the `DRONE` environment variable, which will prompt the test reporter to fallback to `git` to determine commit info:

```bash
if [ "$DRONE_BRANCH" == "master"]; then unset DRONE && codeclimate-test-reporter; fi
```

**Comment by dblandin** [comment]
Hey @krodyrobi,

I just released version `0.1.2` of our python test reporter with a fix for the Drone CI git info which should fix this issue. Sorry for the trouble and thanks again for the report!

**Comment by krodyrobi** [comment]
Wow, thanks for the quick reply, awesome work! I'll check it now.

**Comment by krodyrobi** [comment]
Yep it works! Thanks a million :D.
